---
- name: "PLAY 1: Debug magic variables"
  connection: local
  gather_facts: no
  become: no
  hosts: localhost
  tasks:
    - name: "TASK 1: SYS >> Debug ansible_user"
      debug:
        msg: "{{ ansible_user }}"

    - name: "TASK 2: SYS >> Debug ansible_password"
      debug:
        msg: "{{ ansible_password }}"

    - name: "TASK 3: SYS >> Debug ansible_become_password"
      debug:
        msg: "{{ ansible_become_pass }}"
