---
- name: "PLAY 1: Debug reserved variables"
  connection: network_cli
  gather_facts: no
  become: yes
  become_method: enable
  hosts: r1
  tasks:
    - name: "TASK 1: SYS >> Debug ansible_user"
      debug:
        msg: "{{ ansible_user }}"

    - name: "TASK 2: SYS >> Debug ansible_password"
      debug:
        msg: "{{ ansible_password }}"
