---
# Playbook to demo inheritance of variables
- name: "PLAY 1: WORKING WITH SECRET DATA"
  hosts: all
  connection: network_cli
  tasks:
    - name: "TASK 1: OPEN UP VAULT FILES"
      include_vars: "files/secret_info.yml"
      delegate_to: localhost

    - name: "TASK 2: UNDO NAME SERVER SET"
      ios_config:
        lines:
          - ip name-server 10.250.0.11
          - no ip name-server 1.1.1.1
          - no ip name-server 8.8.8.8
          - no ip name-server 9.9.9.9
          - no ip name-server 10.250.0.1
...
