---
- name: "PLAY 1: First play, run through first"
  connection: local
  gather_facts: no
  become: no
  hosts: localhost
  tags: google, cloudflare
  vars:
    my_first_var: "Ignition!"
  
  tasks:
    - name: "TASK 1: Ping out to defined address: 127.0.0.1"
      shell: "ping 127.0.0.1 -c 3"
      register: ping_output

    - name: "TASK 2: Print output of ping"
      debug:
        var: "ping_output"
...
