---
- name: "PLAY 1: Gather Data from Routers"
  connection: network_cli
  hosts: wan_routers
  tasks:
    - name: "TASK 1: IOS >> Gather Version of the Device"
      ios_command:
        commands:
         - show version
      register: show_version

    - name: "TASK 2: DEBUG >> Command output"
      debug:
        msg: "{{ show_version }}"

    - name: "TASK 3: IOS >> Gather CDP neighbor information"
      ios_command:
        commands:
          - show cdp neighbor
          - show ip route
      register: command_output

    - name: "TASK 4: DEBUG >> Show CDP Neighbor Information"
      debug:
        msg: "{{ command_output }}"

- name: "Play 2: Gather Data from routers with cli_command"
  connection: network_cli
  hosts: wan_routers
  
  tasks:
    - name: "TASK 1: CLI >> Get routing table"
      cli_command:
        command: "show ip route"
      register: cli_output

    - name: "TASK 2: Debug output"
      debug:
        msg: "{{ cli_output }}"

- name: "PLAY 3: NXOS gather info"
  connection: network_cli
  hosts: nxos_switches

  tasks:
    - name: "TASK 1: NXOS >> Get routing table"
      nxos_command:
        commands:
          - show ip route
      register: nxos_output

    - name: "TASK 2: DEBUG >> Nxos output"
      debug:
        msg: "{{ nxos_output }}"
        
      