---
- name: "PLAY 1: Gather Data from Routers"
  connection: network_cli
  hosts: routers
  tasks:
    - name: "TASK 1: IOS >> Gather Version of the Device"
      ios_facts:
        gather_subset:
         - "!config"

    - name: "TASK 2: DEBUG >> Ansible Facts"
      debug:
        msg: "{{ ansible_facts }}"

    - name: "TASK 3: DEBUG >> Print Version"
      debug:
        msg: "{{ ansible_net_version }}"
...