---
- name: "PLAY 1: DEMO MERAKI ENVIRONMENT"
  hosts: meraki_remote
  connection: local
  vars_files:
    - "files/secret_info.yml"
  vars:
    meraki_headers:
      Content-Type: "application/json"
      X-Cisco-Meraki-API-Key: "{{ meraki_key }}"
    net_name: "JoshV"
  tasks:
    - name: "BLOCK 1: ENTIRE PLAY BLOCK"
      block: 
        - name: "TASK 1: Get Meraki Organization ID"
          meraki_organization:
            auth_key: "{{ meraki_key }}"
            state: query
          register: "meraki_org_info"

        - name: debug
          debug:
            msg: "{{ meraki_org_info }}"

        - name: "TASK 2: Get Wireless SSIDs"
          meraki_ssid:
            auth_key: "{{ meraki_key }}"
            net_name: "{{ net_name }}"
            org_id: "{{ meraki_org_info.data.0.id }}"
            state: query
          register: meraki_ssid_pre

        - name: debug ssid_pre
          debug:
            msg: "{{ meraki_ssid_pre }}"

        - name: "TASK 3: Create New Wireless SSID"
          meraki_ssid:
            auth_key: "{{ meraki_key }}"
            net_name: "{{ net_name }}"
            org_name: "{{ meraki_org_info.data.0.name }}"
            state: present
            name: "{{ item.name }}"
            enabled: true
          loop: "{{ wireless }}"
      delegate_to: localhost
...
